version: 2

before:
  hooks:
    - go mod tidy

builds:
  # brr - TUI version (easy cross-compile)
  - id: brr
    main: ./main.go
    binary: brr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  # grr - GUI version for Linux (requires CGO)
  - id: grr-linux
    main: ./grr.go
    binary: grr
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    hooks:
      pre:
        - apt-get update && apt-get install -y libgl1-mesa-dev xorg-dev

  # grr - GUI version for macOS (requires CGO)
  - id: grr-darwin
    main: ./grr.go
    binary: grr
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: brr-archive
    builds:
      - brr
    name_template: "brr_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - sample.txt

  - id: grr-archive
    builds:
      - grr-linux
      - grr-darwin
    name_template: "grr_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - sample.txt

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: metcalfc
    name: brr
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
